### ISSUE TITLE
documentation: Create API Documentation

### ISSUE THREAD

**Issue by MGurcan** [Dijital-Twin/service#10]
### Goal

Effective API documentation for the backend is essential for developers, detailing all endpoints and their required inputs for clear and easy interaction. It should outline how to use these endpoints, the data types they accept, and expected responses, enabling efficient application development.

**Comment by tarik-sarac** [comment]
API documentation is provided by using swagger specification. [Commit Link](https://github.com/Dijital-Twin/service/commit/a443652b041c6ae07f955290225d7fd73923ea61)

Here is an example view of the documentation:

<img width="1263" alt="Screenshot 2024-03-23 at 16 03 40" src="https://github.com/Dijital-Twin/service/assets/78061895/1a7fe138-b649-483b-92ab-3cb20195de92">

As it can be seen on the screenshot above, all endpoints are understandable and user can also see detailed explanation of endpoint and it's inputs:

<img width="1239" alt="Screenshot 2024-03-23 at 16 05 56" src="https://github.com/Dijital-Twin/service/assets/78061895/3bd8a7f9-885c-49ec-805c-534310bf5d38">

Also thanks to swagger, user can also send these requests with authentication token to try out authenticated endpoints. To inject authorize token, simply press Authorize button on the top right page of swagger and it's done!
