### ISSUE TITLE
Create endpoint that request to Haystack QA model

### ISSUE THREAD

**Issue by emirsoyturk** [Dijital-Twin/service#6]

**Comment by MGurcan** [comment]
[Commit URL](https://github.com/Dijital-Twin/service/commit/c43332175ef6c0209b04ccecbd4bf631074f675f#diff-dd105e188f63333f3268f76319ac8b6ba9982f1d85cc9d3e4850d08bc65536d5)

## Goal
Connect Haystack based QA model with our backend.

- We want to find the answers of GPT extracted questions
- QA model will produce the score and the answer corresponding to Question

```
haystackModel = async (question) => {
    const response = await fetch(`http://localhost:${process.env.HAYSTACK_PORT}/get_answer`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({ question: question.question })
    });
    const answer = await response.json();
    return {
        answer: answer.answer,
        score: answer.score
    };
}

module.exports = {
    haystackModel,
}

```
